In [1]:
import pandas as pd 
import numpy as np

In [118]:
df = pd.read_csv('primary_data.csv')
df = df[2:].copy().reset_index(drop=True)

mturk_df = pd.read_csv('primary_mturk_data.csv')

In [119]:
df.columns = ['start_dt_tm',
              'end_dt_tm',
              'status_response_type',
              'ip_address',
              'progress', 
              'duration_seconds',
              'finished',
              'recorded_dt_tm',
              'response_id',
              'recipient_last_name', 
              'recipient_first_name',
              'recipient_email', 
              'external_reference',
              'location_latitude', 
              'location_longitude',
              'distributional_channel',
              'user_language', 
              'gender',
              'geder_text',
              'location',
              'political_identification',
              'political_identification_text',
              'age', 
              'time_first_click_article_control',
              'time_last_click_article_control',
              'time_submit_article_control',
              'click_count_article_control', 
              'time_first_click_article_treatment',
              'time_last_click_article_treatment',
              'time_submit_article_treatment',
              'click_count_article_treatment',
              'point_of_article', 
              'article_factual', 
              'article_effectiveness', 
              'support_tb', 
              'recommend_article', 
              'time_first_click_survey',
              'time_last_click_survey',
              'time_submit_survey',
              'click_count_survey',
              'group',
              'mturk_code']

df.mturk_code.fillna(0, inplace=True)
df['mturk_code'] = df.mturk_code.astype('str')

df['time_first_click_article'] = pd.concat([df.time_first_click_article_control.dropna(),
                                            df.time_first_click_article_treatment.dropna()]).reindex_like(df)

df['time_last_click_article'] = pd.concat([df.time_last_click_article_control.dropna(), 
                                                   df.time_last_click_article_treatment.dropna()]).reindex_like(df)

df['time_submit_article'] = pd.concat([df.time_submit_article_control.dropna(), 
                                       df.time_submit_article_treatment.dropna()]).reindex_like(df)

df['click_count_article'] = pd.concat([df.click_count_article_control.dropna(),
                                       df.click_count_article_treatment.dropna()]).reindex_like(df)

df.drop(['time_first_click_article_control',
         'time_first_click_article_treatment', 
         'time_last_click_article_control', 
         'time_last_click_article_treatment', 
         'click_count_article_control',
         'click_count_article_treatment'], axis=1, inplace=True)

#combine two dataframes together
mturk_df = mturk_df[['Answer.surveycode', 'WorkerId', 'AssignmentId', 'WorkTimeInSeconds']].copy()
mturk_df.columns = ['mturk_code', 'worker_id', 'assignment_id', 'task_time']
mturk_df['mturk_code'] = mturk_df.mturk_code.astype('str')

mturk_df.set_index('mturk_code', inplace=True)

df.set_index('mturk_code', inplace=True)

df = df.join(mturk_df)

df['phase'] = 'Primary'

In [116]:
#placebo_df = df.copy()

In [122]:
#primary_df = df.copy()

In [127]:
combo_df = pd.concat([primary_df, placebo_df])

In [131]:
combo_df.reset_index(inplace=True)

In [133]:
combo_df[combo_df.mturk_code == '83667']

,mturk_code,start_dt_tm,end_dt_tm,status_response_type,ip_address,progress,duration_seconds,finished,recorded_dt_tm,response_id,...,click_count_survey,group,time_first_click_article,time_last_click_article,time_submit_article,click_count_article,worker_id,assignment_id,task_time,phase
177,83667,2018-12-02 18:56:28,2018-12-02 19:00:55,IP Address,71.89.62.152,100,267,True,2018-12-02 19:00:56,R_DC9Q5eLCWNDia41,...,27,Control,3.725,188.543,191.62,34,A3I1ZTAZ8X6RW5,3SB4CE2TJVV33995KCCJTVDDXIHAXC,293.0,Primary
324,83667,2018-12-01 16:46:35,2018-12-01 16:47:45,IP Address,173.44.48.43,100,69,True,2018-12-01 16:47:45,R_2X0eNLGp7ZcOww6,...,5,Control,0,0,3.277,0,A2TT212JCWE13M,3C2NJ6JBKAH9MC0X5RWVPB3HI6VN2T,125.0,Placebo Test

In [134]:
combo_df.worker_id.value_counts()

A2AAG78CGKX2U5    2
A1CPVTZAK27YSF    2
A31GW1DTYUZ9HD    1
AUB4G0UAESKNQ     1
A3LMCFV79DBWJR    1
A9OOTVU0HL5CH     1
AQOCU4H3V27H8     1
A1GOT0DXTYCM4E    1
A33MAJJ3MCBS7Y    1
A2OATZCX1YXE77    1
A2TKHXY755FAM     1
A2TV4MWIOBMNMS    1
A1BMZUNL98C5GL    1
A3DFBZOOWRTQ5M    1
A2Q1JUSJ9THUDZ    1
A2X977GVQ6L90X    1
A2MCRVU8I9VNHG    1
AOZNGVLQA42SZ     1
A7GV4MV5DF3HL     1
A1UEX245I12ZH7    1
AD5PG2OAEDLK5     1
AKX436C0G1LV8     1
A2WXVB5AFTDXSI    1
A1DEDPPSLYETG3    1
A1KRMY3L3ABGJQ    1
A30GJ0HHLO16E8    1
A1PUIGT83JOHH6    1
A198MSVO1VTAT5    1
A49A0FF6ZXYDU     1
A24DH45I5VQKM5    1
                 ..
A19HS6ON7R2KBP    1
A3Q0IEOR5HISHM    1
AI9NU164TZ4Q7     1
A2RSG8IMB0ZOB5    1
AEMGTU4XQ7BKY     1
A2KXUQP1HERQVA    1
A38RJ04DGHZ2QT    1
AO6X3N8DVQYCZ     1
APY7YO8CH0ZDP     1
A2ELH7YDLFNJUZ    1
A1YUK67SL5TWT0    1
A1YMIA0664RNFF    1
A2OEDX14YO8EFJ    1
A2C4R0TBPZGWTD    1
A1CTUG0RUGCY48    1
AM59KUDDHDH5      1
AON59V5VZU2AK     1
API17TMVQ2J7Z     1
A3HL2LL0LEPZT8    1
A3DNL0YLOSIP66    1
A3EXKSF0TKZE1S    1
A3MUG02LJ4BM9F    1
AOWW3URQNRJ6U     1
AT0COJ1G23ZB0     1
A1MO420RJUIT6B    1
A2NKE99I9M8EP3    1
A17HFOEVBHIPQ2    1
A2WVQU5SGS2FBU    1
AGGJZYS099ER3     1
A3MTZ2LRJWZRLD    1
Name: worker_id, Length: 296, dtype: int64

In [139]:
combo_df[combo_df.worker_id.isin(['A2AAG78CGKX2U5', 'A1CPVTZAK27YSF'])]

,mturk_code,start_dt_tm,end_dt_tm,status_response_type,ip_address,progress,duration_seconds,finished,recorded_dt_tm,response_id,...,click_count_survey,group,time_first_click_article,time_last_click_article,time_submit_article,click_count_article,worker_id,assignment_id,task_time,phase
37,19835,2018-12-02 18:53:57,2018-12-02 18:56:36,IP Address,172.58.232.175,100,158,True,2018-12-02 18:56:36,R_2zegFY5aOkcFMdz,...,5,Treatment,0,0,75.603,0,A1CPVTZAK27YSF,3VFJCI1K4ZZKG40WXDY10Z2SUW8GRX,229.0,Primary
126,63300,2018-12-02 18:55:21,2018-12-02 18:55:53,IP Address,96.236.117.160,100,31,True,2018-12-02 18:55:54,R_yju8X2KMZnaPsiJ,...,12,Control,0.447,0.447,1.698,1,A2AAG78CGKX2U5,34YB12FSQYOTJON4S52KE08IO99GM9,182.0,Primary
296,77052,2018-12-01 16:22:14,2018-12-01 16:28:58,IP Address,172.58.232.158,100,403,True,2018-12-01 16:28:58,R_271F2KmPYCDoWLq,...,5,Treatment,0,0,217.133,0,A1CPVTZAK27YSF,3137ONMDKG5V70VRB7E11S39EXZGEG,547.0,Placebo Test
313,55731,2018-12-01 16:31:58,2018-12-01 16:33:43,IP Address,96.236.117.160,100,104,True,2018-12-01 16:33:43,R_6Atzusx3bdUWvDz,...,18,Control,0.64,0.64,2.336,1,A2AAG78CGKX2U5,3S0TNUHWKTIBMFB9WERT3X4QQ2L8DZ,804.0,Placebo Test